services:
  - type: web
    name: epa-feedback-app
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: RESPONSES_DIR
        value: /var/data
      - key: QUALTRICS_DATACENTER
        sync: false
      - key: QUALTRICS_API_TOKEN
        sync: false
      - key: QUALTRICS_SURVEY_ID
        sync: false
      - key: EXPORT_PASSWORD
        sync: false
    disk:
      name: epa-feedback-data
      mountPath: /var/data
      sizeGB: 1
